package main

// псевдонимы городов
var psevdonimy = map[string]string{
	"Сумы":                "Суми",
	"Sumy":                "Суми",
	"Львов":               "Львів",
	"Lviv":                "Львів",
	"Ивано  Франковск":    "Івано Франківськ",
	"Frankivsk":           "Івано Франківськ",
	"Ivano":               "Івано Франківськ",
	"Ivano-Frankivsk":     "Івано Франківськ",
	"Винница":             "Вінниця",
	"Vinnytsia":           "Вінниця",
	"Хмельницкий":         "Хмельницький",
	"Khmelnytskyi":        "Хмельницький",
	"Черновцы":            "Чернівці",
	"Chernivtsi":          "Чернівці",
	"Луцк":                "Луцьк",
	"Lutsk":               "Луцьк",
	"Ровно":               "Рівне",
	"Rivne":               "Рівне",
	"Ужгород":             "Ужгород",
	"Uzhhorod":            "Ужгород",
	"Житомир":             "Житомир",
	"Zhytomyr":            "Житомир",
	"Днепр":               "Дніпро",
	"Dnipro":              "Дніпро",
	"Dnipropetrovsk":      "Дніпро",
	"Черкассы":            "Черкаси",
	"Cherkasy":            "Черкаси",
	"Полтава":             "Полтава",
	"Poltava":             "Полтава",
	"Одесса":              "Одеса",
	"Odesa":               "Одеса",
	"Кривий Ріг":          "Кривий Ріг",
	"Кривой Рог":          "Кривий Ріг",
	"Kr":                  "Кривий Ріг",
	"Kryvyi Rih":          "Кривий Ріг",
	"Kryvyi":              "Кривий Ріг",
	"Запорожье":           "Запоріжжя",
	"Zaporizhia":          "Запоріжжя",
	"Zaporizhzhia":        "Запоріжжя",
	"Киев":                "Київ",
	"Kyiv":                "Київ",
	"Тернополь":           "Тернопіль",
	"Ternopil":            "Тернопіль",
	"Чернигов":            "Чернігів",
	"Chernihiv":           "Чернігів",
	"Харків":              "Харків",
	"Харьков":             "Харків",
	"Kharkiv":             "Харків",
	"Херсон":              "Херсон",
	"Kherson":             "Херсон",
	"Варшава":             "Варшава",
	"Мукачево":            "Мукачево",
	"Камянец":             "Камянец",
	"Kamianets_Podilskyi": "Камянец",
	"Warshawa":            "Варшава",
	"Mukachevo":           "Мукачево",
}

var City_Name = map[string]string{
	"Київ":             "Kyiv",
	"Дніпро":           "Dnipro",
	"Запоріжжя":        "Zaporizhia",
	"Одеса":            "Odesa",
	"Івано Франківськ": "Ivano",
	"Суми":             "Sumy",
	"Полтава":          "Poltava",
	"Луцьк":            "Lutsk",
	"Ужгород":          "Uzhhorod",
	"Черкаси":          "Cherkasy",
	"Чернігів":         "Chernihiv",
	"Чернівці":         "Chernivtsi",
	"Львів":            "Lviv",
	"Кривий Ріг":       "Kryvyi",
	"Рівне":            "Rivne",
	"Вінниця":          "Vinnytsia",
	"Житомир":          "Zhytomyr",
	"Хмельницький":     "Khmelnytskyi",
	"Тернопіль":        "Ternopil",
	"Мукачево":         "Mukachevo",
	"Камянец":          "Kamianets_Podilskyi",
	"Харків":           "Kharkiv",
	"Херсон":           "Kherson",
	"Варшава":          "Warsaw",
}

var City_Name_Reverse = map[string]string{
	"Kyiv":                "Київ",
	"Dnipro":              "Дніпро",
	"Zaporizhia":          "Запоріжжя",
	"Odesa":               "Одеса",
	"Ivano":               "Івано Франківськ",
	"Sumy":                "Суми",
	"Poltava":             "Полтава",
	"Lutsk":               "Луцьк",
	"Uzhhorod":            "Ужгород",
	"Cherkasy":            "Черкаси",
	"Chernihiv":           "Чернігів",
	"Chernivtsi":          "Чернівці",
	"Lviv":                "Львів",
	"Kryvyi":              "Кривий Ріг",
	"Rivne":               "Рівне",
	"Vinnytsia":           "Вінниця",
	"Zhytomyr":            "Житомир",
	"Khmelnytskyi":        "Хмельницький",
	"Ternopil":            "Тернопіль",
	"Mukachevo":           "Мукачево",
	"Kamianets_Podilskyi": "Камянец",
	"Kharkiv":             "Харків",
	"Kherson":             "Херсон",
	"Warsaw":              "Варшава",
}

// построение списка парков
// по всей Украине
func create_sitys() []sity {

	return City_Park_G_Car.m

}

func create_sitys_test() []sity {
	return create_sitys()[5:6]
}
